### ISSUE TITLE
Topic for your reposotiry

### ISSUE THREAD

**Issue by EPTamminga** [Tychodewaard/sticky-notes#1]
## Suggestion

Add GitHub **topics** to the title of your repository, so that the repo can be found more easily.
See: [GitHub Topics Help](https://help.github.com/articles/about-topics/).

Ideas for relevant topics: dnn; dotnetnuke; dnnplatform;  dnncms

If your repo is a **theme**, add topics like: theme; skin

Add or enhance the readme.md file, so that people can see what the repo is about.

**Comment by Tychodewaard** [comment]
Done
